---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-361 A} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Worksheet 2} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Statistical Thinking

**Scenario:** Researchers conducted a study to understand whether drinking coffee impacts productivity at work. They collected data on how much coffee people drink daily and how productive they feel during their workday. The study examined whether there is a consistent pattern between coffee consumption and productivity levels.

**Discussion Questions:** Write your individual answers for the following questions on paper, then discuss them with your peers.

1. What is the main focus of the study?
\vfill
2. How might coffee consumption affect productivity, based on your intuition?
\vfill
3. What could a strong relationship between coffee consumption and productivity suggest for coffee drinkers?
\vfill
4. What other factors (confounders) might influence both coffee consumption and productivity? How could these affect the study's conclusions?
\vfill
5. If the study finds a meaningful connection, what practical advice could it offer to workers?
\vfill

<!-- \newpage

## **References**

::: {#refs}
:::

<br> -->
